<#
.SYNOPSIS
  Sets up the Jarvis autonomous daemon to run unattended at logon, and optionally starts it now.

.DESCRIPTION
  Prefers a Windows Scheduled Task (auto-restart on failure). If that registration is denied
  (no Administrator rights), it falls back to a per-user Startup-folder launcher that needs no
  elevation. Either way the daemon supervises heartbeat, order-watch, watchdog, and IGM on their
  configured cadences. Respects the DRY_RUN / REQUIRE_APPROVAL values in .env -- this installer
  never changes operating mode.

.PARAMETER Uninstall
  Removes both the scheduled task and the Startup-folder launcher.

.PARAMETER Start
  Also launches the daemon immediately (hidden), in addition to installing autostart.

.PARAMETER AtStartup
  For the scheduled-task path, also trigger at system startup (in addition to user logon).

.PARAMETER TaskName
  Scheduled task name. Defaults to "JarvisEtsyDaemon".
#>
param(
  [switch]$Uninstall,
  [switch]$Start,
  [switch]$AtStartup,
  [string]$TaskName = "JarvisEtsyDaemon"
)

$ErrorActionPreference = "Stop"

$projectRoot = Split-Path -Parent $PSScriptRoot
$logDir = Join-Path $projectRoot "data"
$outLog = Join-Path $logDir "daemon.out.log"
$runnerCmd = Join-Path $PSScriptRoot "run-daemon.cmd"
$startupDir = [Environment]::GetFolderPath('Startup')
$startupLauncher = Join-Path $startupDir "JarvisEtsyDaemon.vbs"

if ($Uninstall) {
  $existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
  if ($existing) {
    try { Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false; Write-Host "Removed scheduled task '$TaskName'." -ForegroundColor Green }
    catch { Write-Warning "Could not remove scheduled task '$TaskName': $($_.Exception.Message)" }
  }
  if (Test-Path -LiteralPath $startupLauncher) {
    Remove-Item -LiteralPath $startupLauncher -Force
    Write-Host "Removed Startup launcher: $startupLauncher" -ForegroundColor Green
  }
  Write-Host "Jarvis daemon autostart removed. (Any running daemon process is not stopped here.)" -ForegroundColor Cyan
  return
}

$npmCommand = Get-Command npm.cmd -ErrorAction SilentlyContinue
if (-not $npmCommand) {
  throw "npm.cmd was not found on PATH. Install Node.js (which provides npm) before installing the daemon."
}
if (-not (Test-Path -LiteralPath $logDir)) {
  New-Item -ItemType Directory -Path $logDir | Out-Null
}

# Creates a per-user Startup-folder launcher that runs the daemon hidden at logon (no admin required).
function New-StartupLauncher {
  $vbs = @"
' Auto-generated by install-daemon-task.ps1 -- launches the Jarvis daemon hidden at logon.
Set sh = CreateObject("WScript.Shell")
sh.Run Chr(34) & "$runnerCmd" & Chr(34), 0, False
"@
  Set-Content -LiteralPath $startupLauncher -Value $vbs -Encoding ASCII
}

$installedVia = ""

try {
  $npmPath = $npmCommand.Source
  $innerCommand = "Set-Location -LiteralPath '$projectRoot'; & '$npmPath' run daemon *>> '$outLog'"
  $encoded = [Convert]::ToBase64String([System.Text.Encoding]::Unicode.GetBytes($innerCommand))

  $action = New-ScheduledTaskAction -Execute "powershell.exe" `
    -Argument "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -EncodedCommand $encoded" `
    -WorkingDirectory $projectRoot

  $triggers = @(New-ScheduledTaskTrigger -AtLogOn)
  if ($AtStartup) { $triggers += New-ScheduledTaskTrigger -AtStartup }

  $principal = New-ScheduledTaskPrincipal -UserId ([System.Security.Principal.WindowsIdentity]::GetCurrent().Name) -LogonType Interactive -RunLevel Limited
  $settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable `
    -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 2) `
    -ExecutionTimeLimit (New-TimeSpan -Seconds 0) -MultipleInstances IgnoreNew

  $existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
  if ($existing) { Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false }

  Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $triggers -Principal $principal -Settings $settings `
    -Description "Jarvis Etsy autonomous daemon (heartbeat, order-watch, watchdog, IGM)." -ErrorAction Stop | Out-Null

  $installedVia = "scheduled-task"
  # Avoid double autostart: drop any prior Startup-folder launcher now that the task owns autostart.
  if (Test-Path -LiteralPath $startupLauncher) { Remove-Item -LiteralPath $startupLauncher -Force }
  Write-Host "Installed scheduled task '$TaskName' (auto-restarts every 2 min)." -ForegroundColor Green
} catch {
  Write-Warning "Scheduled task registration unavailable ($($_.Exception.Message))."
  Write-Host "Falling back to a per-user Startup launcher (no admin needed)." -ForegroundColor Yellow
  New-StartupLauncher
  $installedVia = "startup-folder"
  Write-Host "Installed Startup launcher: $startupLauncher" -ForegroundColor Green
  Write-Host "Tip: to use the more robust scheduled task instead, re-run this from an elevated PowerShell." -ForegroundColor Cyan
}

if ($Start) {
  Start-Process -FilePath $runnerCmd -WorkingDirectory $projectRoot -WindowStyle Hidden | Out-Null
  Write-Host "Started the daemon now (hidden)." -ForegroundColor Green
}

Write-Host ""
Write-Host "Autostart method: $installedVia. Console output: $outLog" -ForegroundColor Cyan
Write-Host "Structured logs: $(Join-Path $logDir 'jarvis.log')" -ForegroundColor Cyan
Write-Host "Remove with: npm run uninstall-daemon" -ForegroundColor Cyan
